### ISSUE TITLE
find_element_by_id error with x64 docker image

### ISSUE THREAD

**Issue by davidpickel** [eyalcha/read_your_meter#8]
home assistant os: 2022.7.4
read_your_meter: 1.0.12

```
read_your_meter:
  host: http://192.168.x.x:4444
  username: x@x.com
  password: xxxx
  daily:
    - 0
    - 1
    - 2
    - 3
  monthly:
    - 0
    - 1
    - 2
    - 3
```

running on x64 with selenium/standalone-chrome:latest results with 
`'WebDriver' object has no attribute 'find_element_by_id'`
tried older versions of docker image with the same results. 

 
logs: 
2022-07-15 09:53:55 ERROR (MainThread) [custom_components.read_your_meter.sensor] Error fetching sensor data: Error communicating with server: 'WebDriver' object has no attribute 'find_element_by_id'
